fix: fixing null bug in tempr map
open-interop/oop-core-interface pull request #161
Opened 2020-08-26 11:20 UTC by benarmstrongbf

2020-08-26 13:38 UTC, danyoung93 requested changes

2020-08-26 13:38 UTC, danyoung93 commented on src/components/View/Tempr.js
> +            }
In JS it's probably not worth aiming for the backwards loops optimization, it won't really improve things much if anything because JS is interpreted. (Also, I think that optimization only works when the condition is `i != 0` to get the jump zero optimization).

Also, if you're optimizing the iteration condition, you probably want a break on the `none = false;` to quit the loop as soon as you there are children.

I'd write this loop something like this in JS;

```
for (const tempr of response.data) {
    if (tempr.temprId === temprId) {
        setNoChildren(false);
        return;
    }
    setNoChildren(true);
}
```

2020-08-26 13:38 UTC, danyoung93 commented on src/components/View/TemprMap.js
> +        }
Similar to above for this loop.

2020-08-26 13:38 UTC, danyoung93 commented on src/components/View/TemprMap.js
> +			const unique_paths = [...new Set(paths)];
This is using the `paths` variable from the outer scope, I wouldn't modify this as it could cause weird things to happen.

Maybe user an inner scoped variable like `pathSet`, also, if you make it a set from the beginning rather than going array -> set -> array, it'll be much quicker.

2020-08-26 13:38 UTC, danyoung93 commented on src/components/View/TemprMap.js
>  import React, { useState, useEffect, memo } from "react";
This file seems to have a mix of tabs and spaces, which is making it render weirdly on github. As standard we use 4 space indents.

2020-08-26 14:20 UTC, benarmstrongbf commented on src/components/View/Tempr.js
> +            }
Yeah good point I think I just auto-completed on sublime for the for loop to get the backwards loop

2020-08-28 10:03 UTC, jackregnart approved these changes

2020-08-28 10:10 UTC, danyoung93 approved these changes

2020-08-28 16:15 UTC, merged